# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
      path: /h2
  cloud:
    stream:
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      bindings:
#        input:
        input-city-data:
          destination: city-details
          content-type: application/*+avro
#          group: group-1
          consumer:
            concurrency: 3
        output:
          destination: city-details
          content-type: application/*+avro
      kafka:
        binder:
          brokers: localhost:9092 # brokers do kakfa, separados por virgula
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://localhost:8081
          consumer-properties:
            key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://localhost:8081
            specific.avro.reader: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 5
      max-life-time: 20000 #20s
      connection-timeout: 30000 #30s
      idle-timeout: 30000 #30s
      pool-name: treinamento-pool
      auto-commit: false

## loggin

logging:
  level:
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
