# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 5
      max-life-time: 20000 #20s
      connection-timeout: 30000 #30s
      idle-timeout: 30000 #30s
      pool-name: treinamento-pool
      auto-commit: false

## loggin

logging:
  level:
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG